# [↩️ 리스트로 돌아가기](https://dacon.io/competitions/open/235698/overview/description)

# 셀을 실행할 때 팝업이 뜨면 `무시하고 계속하기` 를 눌러주세요

## 데이터 다운로드
--- 
아래 셀을 실행시켜 데이터를 colab에 불러옵니다.  
셀 실행은 Ctrl + Enter 를 이용해 실행 시킬 수 있습니다.

In [1]:
# 데이터 다운로드 링크로 데이터를 코랩에 불러옵니다.

!wget 'https://bit.ly/3gLj0Q6'

import zipfile
with zipfile.ZipFile('3gLj0Q6', 'r') as existing_zip:
    existing_zip.extractall('data')

--2022-09-29 09:15:35--  https://bit.ly/3gLj0Q6
Resolving bit.ly (bit.ly)... 67.199.248.10, 67.199.248.11
Connecting to bit.ly (bit.ly)|67.199.248.10|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://drive.google.com/uc?export=download&id=1or_QN1ksv81DNog6Tu_kWcZ5jJWf5W9E [following]
--2022-09-29 09:15:35--  https://drive.google.com/uc?export=download&id=1or_QN1ksv81DNog6Tu_kWcZ5jJWf5W9E
Resolving drive.google.com (drive.google.com)... 173.194.202.113, 173.194.202.100, 173.194.202.101, ...
Connecting to drive.google.com (drive.google.com)|173.194.202.113|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://doc-0c-10-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/dbbn99paflam9b42b3tjmn03201phkf0/1664442900000/17946651057176172524/*/1or_QN1ksv81DNog6Tu_kWcZ5jJWf5W9E?e=download&uuid=dd014750-b752-4cb7-89b0-f1b151c82a5d [following]
Warning: wildcards not supported in HTTP.
--2022-09-29 09:15:36--  https://doc-0c-10-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/dbbn99paflam9b42b3tjmn03201phkf0/1664442900000/17946651057176172524/*/1or_QN1ksv81DNog6Tu_kWcZ5jJWf5W9E?e=download&uuid=dd014750-b752-4cb7-89b0-f1b151c82a5d
Resolving doc-0c-10-docs.googleusercontent.com (doc-0c-10-docs.googleusercontent.com)... 74.125.195.132, 2607:f8b0:400e:c09::84
Connecting to doc-0c-10-docs.googleusercontent.com (doc-0c-10-docs.googleusercontent.com)|74.125.195.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 39208 (38K) [application/zip]
Saving to: ‘3gLj0Q6’

3gLj0Q6             100%[===================>]  38.29K  --.-KB/s    in 0.001s

2022-09-29 09:15:36 (27.0 MB/s) - ‘3gLj0Q6’ saved [39208/39208]

## 실습
---
head() 메서드를 이용해 `train 데이터의 상위 10개 행을 출력`해 보세요.

In [ ]:
import pandas as pd

train = pd.read_csv('data/train.csv') 
'train 데이터의 상위 10개 행을 출력하는 코드 작성'

'train 데이터의 상위 10개 행을 출력하는 코드 작성'

In [2]:
import pandas as pd

train = pd.read_csv('data/train.csv') 
train.head(10)

,id,hour,hour_bef_temperature,hour_bef_precipitation,hour_bef_windspeed,hour_bef_humidity,hour_bef_visibility,hour_bef_ozone,hour_bef_pm10,hour_bef_pm2.5,count
0,3,20,16.3,1.0,1.5,89.0,576.0,0.027,76.0,33.0,49.0
1,6,13,20.1,0.0,1.4,48.0,916.0,0.042,73.0,40.0,159.0
2,7,6,13.9,0.0,0.7,79.0,1382.0,0.033,32.0,19.0,26.0
3,8,23,8.1,0.0,2.7,54.0,946.0,0.040,75.0,64.0,57.0
4,9,18,29.5,0.0,4.8,7.0,2000.0,0.057,27.0,11.0,431.0
5,13,2,13.6,0.0,1.7,80.0,1073.0,0.027,34.0,15.0,39.0
6,14,3,10.6,0.0,1.5,58.0,1548.0,0.038,62.0,33.0,23.0
7,16,21,16.0,0.0,6.0,21.0,1961.0,0.050,90.0,28.0,146.0
8,19,9,13.8,0.0,1.9,64.0,1344.0,0.039,93.0,19.0,39.0
9,20,14,17.2,0.0,2.1,32.0,1571.0,0.025,64.0,19.0,83.0

## 정답
---
스스로 실습 코드를 작성 한 후 정답 코드를 확인해 보세요.

In [ ]:
import pandas as pd

train = pd.read_csv('data/train.csv')

# 정답 코드
train.head(100)

    id       datetime  temperature  precipitation  ...  ozone  pm10  pm2.5  count
0    0  2017-04-01-00          4.9              0  ...    NaN   NaN    NaN   39.0
1    1  2017-04-01-01          5.1              0  ...  0.018  16.0    NaN   34.0
2    2  2017-04-01-02          5.7              0  ...  0.032  12.0   13.0   29.0
3    3  2017-04-01-03          5.7              0  ...  0.028  14.0   18.0   21.0
4    4  2017-04-01-04          5.5              0  ...  0.022  18.0    NaN    6.0
..  ..            ...          ...            ...  ...    ...   ...    ...    ...
95  95  2017-04-04-23         13.6              0  ...  0.055  76.0   66.0   91.0
96  96  2017-04-05-00         13.3              0  ...    NaN   NaN    NaN   47.0
97  97  2017-04-05-01         13.2              0  ...  0.033  60.0   51.0   34.0
98  98  2017-04-05-02         12.8              0  ...  0.016  94.0   82.0   26.0
99  99  2017-04-05-03         12.3              0  ...  0.024  96.0   90.0   15.0

[100 rows x 11 columns]

# [↩️ 리스트로 돌아가기](https://dacon.io/competitions/open/235698/overview/description)